name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/common-actions/install

      - name: Check for Changesets
        id: check
        run: |
          CHANGESET_FILES=$(ls .changeset/*.md 2>/dev/null | grep -v README.md || true)
          echo "has-changesets=$([ -n "$CHANGESET_FILES" ] && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Create/Update Version PR (generic title)
        if: steps.check.outputs.has-changesets == 'true'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm changeset:publish
          createGithubReleases: true
          title: "ci(changesets): version packages"
          commit: "ci(changesets): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update PR title with the actual version
        if: steps.changesets.outputs.pullRequestNumber != ''
        env:
          GH_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
        run: |
          PR_NUMBER=${{ steps.changesets.outputs.pullRequestNumber }}
          HEAD_REF=$(gh pr view "$PR_NUMBER" --json headRefName -q .headRefName)
          git fetch origin "$HEAD_REF"
          VERSION="v$(git show "origin/$HEAD_REF:package.json" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync(0,'utf8')).version)")"
          gh pr edit "$PR_NUMBER" --title "chore(release): bump version to $VERSION"

      - name: Enable PR auto-merge
        if: steps.changesets.outputs.pullRequestNumber != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.CHANGESETS_TOKEN }}
          pull-request-number: ${{ steps.changesets.outputs.pullRequestNumber }}
          merge-method: squash

      - name: Check for Version Changes
        if: steps.check.outputs.has-changesets == 'false'
        id: version-check
        run: |
          NAME=$(node -p "require('./package.json').name")
          CURRENT=$(node -p "require('./package.json').version")
          PUBLISHED=$(npm view "$NAME" version 2>/dev/null || echo "0.0.0")
          echo "pkg-name=$NAME" >> $GITHUB_OUTPUT
          echo "should-publish=$([ "$CURRENT" != "$PUBLISHED" ] && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Configure npm auth
        if: steps.version-check.outputs.should-publish == 'true'
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        if: steps.check.outputs.has-changesets == 'false' && steps.version-check.outputs.should-publish == 'true'
        run: pnpm changeset:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release (no-changeset path)
        if: steps.check.outputs.has-changesets == 'false' && steps.version-check.outputs.should-publish == 'true'
        env:
          GH_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}
        run: |
          VERSION="v$(node -p "require('./package.json').version")"
          gh release create "$VERSION" --title "Release $VERSION" --generate-notes
